[workspace]
resolver = "2"
members = [
    "src/Blun.Mq.Host",
    "src/Blun.Mq.Proto",
    "src/Blun.Mq.Raft",
    "src/Blun.Mq.Client",
    "src/demo/producer",
    "src/demo/consumer",
    "src/demo/bench",
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
tonic-build = "0.12"
prost = "0.13"
bytes = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = { version = "0.7", features = ["ws"] }
futures = "0.3"
tokio-stream = "0.1"
async-stream = "0.3"
tower-http = { version = "0.5", features = ["cors"] }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
raft-engine = "0.4"
protobuf = "=3.7"
