[package]
name = "mq-demo-consumer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mq-demo-consumer"
path = "src/main.rs"

[dependencies]
mq-client = { path = "../../Blun.Mq.Client" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
