pub mod log_store;
pub mod network;
// Generated by build.rs from proto/raft_log_entry.proto (build.rs also
// strips the `#![allow(...)]` header protobuf-codegen emits, since those
// inner attributes aren't legal when spliced in via `include!`).
#[allow(warnings)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/raft_log_entry.rs"));
}
pub mod raft_engine_log_store;
pub mod state_machine;
pub mod types;

pub use log_store::LogStore;
pub use network::{Network, NetworkConnection, PeerAddresses};
pub use raft_engine_log_store::RaftEngineLogStore;
pub use state_machine::{QueueState, StateMachineStore};
pub use types::{QueueRequest, QueueResponse, TypeConfig};

pub type Raft = openraft::Raft<TypeConfig>;

pub fn raft_config() -> openraft::Config {
    openraft::Config {
        heartbeat_interval: 500,
        election_timeout_min: 1500,
        election_timeout_max: 3000,
        ..Default::default()
    }
}
