pub mod network;
pub mod node_state_machine;
// Generated by build.rs from proto/raft_log_entry.proto (build.rs also
// strips the `#![allow(...)]` header protobuf-codegen emits, since those
// inner attributes aren't legal when spliced in via `include!`).
#[allow(warnings)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/raft_log_entry.rs"));
}
pub mod raft_engine_log_store;
pub mod state_machine;
pub mod types;

pub use network::{Network, NetworkConnection, PeerAddresses};
pub use node_state_machine::{NodeDirectory, NodeStateMachineStore};
pub use raft_engine_log_store::RaftEngineLogStore;
pub use state_machine::{QueueState, StateMachineStore};
pub use types::{
    NodeCommand, NodeResponse, NodeTypeConfig, QueueRequest, QueueResponse, QueueTypeConfig,
};

pub use mq_proto::RaftGroup;

/// The cluster-membership/directory Raft group's handle. Small, low-churn,
/// backed by its own WAL.
pub type NodeRaft = openraft::Raft<NodeTypeConfig>;
/// The "spam" queue's data Raft group's handle. High-churn (every
/// publish/pop goes through it), backed by its own, separate WAL.
pub type QueueRaft = openraft::Raft<QueueTypeConfig>;

pub fn raft_config() -> openraft::Config {
    openraft::Config {
        heartbeat_interval: 500,
        election_timeout_min: 1500,
        election_timeout_max: 3000,
        ..Default::default()
    }
}
